In [1]:
import pandas as pd
import utm

In [2]:
pd.set_option('display.precision', 10)

In [3]:
f_name = "validationData"

In [4]:
df = pd.read_csv("uji/raw_data/UJIndoorLoc/data/{}.csv".format(f_name))

In [5]:
df[["LONGITUDE", "LATITUDE"]] = df[["LONGITUDE", "LATITUDE"]]/100000
df

,WAP001,WAP002,WAP003,WAP004,WAP005,WAP006,WAP007,WAP008,WAP009,WAP010,...,WAP520,LONGITUDE,LATITUDE,FLOOR,BUILDINGID,SPACEID,RELATIVEPOSITION,USERID,PHONEID,TIMESTAMP
0,100,100,100,100,100,100,100,100,100,100,...,100,-0.0751591680,48.6488966292,1,1,0,0,0,0,1380872703
1,100,100,100,100,100,100,100,100,100,100,...,100,-0.0738386722,48.6483974031,4,2,0,0,0,13,1381155054
2,100,100,100,100,100,100,100,100,100,100,...,100,-0.0737430208,48.6484653372,4,2,0,0,0,13,1381155095
3,100,100,100,100,100,100,100,100,100,100,...,100,-0.0736582488,48.6484282925,4,2,0,0,0,13,1381155138
4,100,100,100,100,100,100,100,100,100,100,...,100,-0.0764149930,48.6492239918,2,0,0,0,0,2,1380877774
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1106,100,100,100,100,100,100,100,100,100,100,...,100,-0.0731734423,48.6479553006,3,2,0,0,0,13,1381156711
1107,100,100,100,100,100,100,100,100,100,100,...,100,-0.0731373112,48.6479206341,3,2,0,0,0,13,1381156730
1108,100,100,100,100,100,100,100,100,100,100,...,100,-0.0763753580,48.6490322942,0,0,0,0,0,13,1381247781
1109,100,100,100,100,100,100,100,100,100,100,...,100,-0.0763665401,48.6490493586,0,0,0,0,0,13,1381247807
1110,100,100,100,100,100,100,100,100,100,100,...,100,-0.0763794412,48.6490353590,0,0,0,0,0,13,1381247836

In [6]:
df[['x', 'y']] = df.apply(lambda row: pd.Series(utm.from_latlon(row['LATITUDE'], row['LONGITUDE'])[:2]), axis=1)
df

,WAP001,WAP002,WAP003,WAP004,WAP005,WAP006,WAP007,WAP008,WAP009,WAP010,...,LATITUDE,FLOOR,BUILDINGID,SPACEID,RELATIVEPOSITION,USERID,PHONEID,TIMESTAMP,x,y
0,100,100,100,100,100,100,100,100,100,100,...,48.6488966292,1,1,0,0,0,0,1380872703,715418.0863673664,5.3925556369e+06
1,100,100,100,100,100,100,100,100,100,100,...,48.6483974031,4,2,0,0,0,13,1381155054,715517.4607768450,5.3925038835e+06
2,100,100,100,100,100,100,100,100,100,100,...,48.6484653372,4,2,0,0,0,13,1381155095,715524.2151945623,5.3925117040e+06
3,100,100,100,100,100,100,100,100,100,100,...,48.6484282925,4,2,0,0,0,13,1381155138,715530.6161086694,5.3925078264e+06
4,100,100,100,100,100,100,100,100,100,100,...,48.6492239918,2,0,0,0,0,2,1380877774,715324.2086466715,5.3925884737e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1106,100,100,100,100,100,100,100,100,100,100,...,48.6479553006,3,2,0,0,0,13,1381156711,715568.3366531376,5.3924566282e+06
1107,100,100,100,100,100,100,100,100,100,100,...,48.6479206341,3,2,0,0,0,13,1381156730,715571.1453817642,5.3924528775e+06
1108,100,100,100,100,100,100,100,100,100,100,...,48.6490322942,0,0,0,0,0,13,1381247781,715327.9442825908,5.3925672803e+06
1109,100,100,100,100,100,100,100,100,100,100,...,48.6490493586,0,0,0,0,0,13,1381247807,715328.5209509835,5.3925692018e+06
1110,100,100,100,100,100,100,100,100,100,100,...,48.6490353590,0,0,0,0,0,13,1381247836,715327.6305238249,5.3925676094e+06

In [7]:
df[['x_scaled']] = df[['x']] - df[['x']].mean()
df[['y_scaled']] = df[['y']] - df[['y']].mean()
df

,WAP001,WAP002,WAP003,WAP004,WAP005,WAP006,WAP007,WAP008,WAP009,WAP010,...,BUILDINGID,SPACEID,RELATIVEPOSITION,USERID,PHONEID,TIMESTAMP,x,y,x_scaled,y_scaled
0,100,100,100,100,100,100,100,100,100,100,...,1,0,0,0,0,1380872703,715418.0863673664,5.3925556369e+06,10.3020326978,-13.2564718071
1,100,100,100,100,100,100,100,100,100,100,...,2,0,0,0,13,1381155054,715517.4607768450,5.3925038835e+06,109.6764421765,-65.0099246185
2,100,100,100,100,100,100,100,100,100,100,...,2,0,0,0,13,1381155095,715524.2151945623,5.3925117040e+06,116.4308598938,-57.1894201143
3,100,100,100,100,100,100,100,100,100,100,...,2,0,0,0,13,1381155138,715530.6161086694,5.3925078264e+06,122.8317740009,-61.0670114774
4,100,100,100,100,100,100,100,100,100,100,...,0,0,0,0,2,1380877774,715324.2086466715,5.3925884737e+06,-83.5756879970,19.5803346680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1106,100,100,100,100,100,100,100,100,100,100,...,2,0,0,0,13,1381156711,715568.3366531376,5.3924566282e+06,160.5523184690,-112.2652259991
1107,100,100,100,100,100,100,100,100,100,100,...,2,0,0,0,13,1381156730,715571.1453817642,5.3924528775e+06,163.3610470956,-116.0159377353
1108,100,100,100,100,100,100,100,100,100,100,...,0,0,0,0,13,1381247781,715327.9442825908,5.3925672803e+06,-79.8400520778,-1.6130568022
1109,100,100,100,100,100,100,100,100,100,100,...,0,0,0,0,13,1381247807,715328.5209509835,5.3925692018e+06,-79.2633836850,0.3083773721
1110,100,100,100,100,100,100,100,100,100,100,...,0,0,0,0,13,1381247836,715327.6305238249,5.3925676094e+06,-80.1538108436,-1.2839678898

In [8]:
df.to_csv("{}.csv".format(f_name))

In [2]:
import torch

ModuleNotFoundError: No module named 'torch'

In [2]:
def get_known_mask_new(known_prob, edge_num):
    known_mask = (torch.FloatTensor(edge_num, 1).uniform_() < known_prob).view(-1)
    return known_mask

In [3]:
get_known_mask_new(0.7, 10)

NameError: name 'torch' is not defined